# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='i_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='u_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_deleted',
            field=models.CharField(blank=True, default=b'n', max_length=1, null=True),
        ),
    ]
