# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('i_by', models.IntegerField(blank=True, null=True)),
                ('u_by', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_id', models.CharField(blank=True, max_length=255, null=True)),
                ('job_startdate', models.CharField(blank=True, max_length=255, null=True)),
                ('job_enddate', models.CharField(blank=True, max_length=255, null=True)),
                ('job_source', models.CharField(blank=True, max_length=255, null=True)),
                ('job_destination', models.CharField(blank=True, max_length=255, null=True)),
                ('job_status', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
    ]
