# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_nbr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
