# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20170324_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_status',
            field=models.CharField(blank=True, default='p', max_length=255, null=True),
        ),
    ]
