# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('group_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
    ]
