# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vin_no', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_year', models.CharField(blank=True, max_length=255, null=True)),
                ('vehicle_license', models.CharField(blank=True, max_length=255, null=True)),
                ('registration_state', models.CharField(blank=True, max_length=255, null=True)),
                ('vehiclestatus_id', models.IntegerField(blank=True, null=True)),
                ('group_id', models.IntegerField(blank=True, null=True)),
                ('contact_id', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.CharField(blank=True, default='n', max_length=1, null=True)),
                ('ownership', models.CharField(blank=True, max_length=255, null=True)),
                ('company_id', models.CharField(blank=True, max_length=255, null=True)),
                ('i_by', models.IntegerField(blank=True, null=True)),
                ('u_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='VehicleDocument',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('vehicle_id', models.IntegerField(blank=True, null=True)),
                ('doc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_date', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_type', models.CharField(blank=True, max_length=255, null=True)),
                ('doc_location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
        migrations.CreateModel(
            name='VehicleStatus',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id', models.AutoField(db_index=True, primary_key=True, serialize=False)),
                ('vehicle_id', models.IntegerField(blank=True, null=True)),
                ('vehiclestatus_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'abstract': False,
                'get_latest_by': 'modified',
            },
        ),
    ]
