# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20170317_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclestatus',
            name='i_by',
        ),
        migrations.RemoveField(
            model_name='vehiclestatus',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='vehiclestatus',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='vehiclestatus',
            name='u_by',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='contact_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='group_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehiclestatus_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
